### ISSUE TITLE
Votes table and vote counter cache

### ISSUE THREAD

**Issue by bcardarella** [ElixirMostWanted/elixirmostwanted.com#10]
`votes`

`wanted_id` foreign key to the `wanteds` table
`user_id` foreign key to the `users` table

on the `wanteds` table add

`vote_count` - `int`

there should be a db trigger for each insert on the `votes` table that recalculates the related `wanted.votes` tally and sets that counter cace.

No blockers

**Comment by Alvinkariuki** [comment]
I'd like to take this up

**Comment by aptinio** [comment]
I suggest naming the count column as `vote_count` so we can still do `has_many :votes` for `User`.
